kafka-text-message:
  topic: 'income_message'
  delayOnErrorMillis: 1_000
  pollIntervalMillis: 1_000
  consumer:
    "[bootstrap.servers]": " 172.24.92.220:9092"
    "[client.id]": 'bookworm-telegram-msg-proc'
    "[group.id]": 'bookworm-telegram-msg-proc'
    "[max.pool.size]": 10
kafka-text-response:
  topic: 'text_response'
  producer:
    "[bootstrap.servers]": " 172.24.92.220:9092"
    "[client.id]": 'bookworm-telegram-msg-proc'
facade:
    host: localhost
    port: 8090