//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.10 at 10:52:05 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.gribuser.ru/xml/fictionbook/2.0", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.jaxb.fb2;
