//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.09 at 11:16:16 PM MSK 
//


package org.jaxb.fb2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.NormalizedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Корневой элемент для единичного блока выделения
 * 
 * <p>Java class for SelectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SelectionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Note" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="p" type="{http://www.gribuser.ru/xml/fictionbook/2.0}pType"/&gt;
 *                   &lt;element name="empty-line" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Extract" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="p" type="{http://www.gribuser.ru/xml/fictionbook/2.0}pType"/&gt;
 *                   &lt;element name="image" type="{http://www.gribuser.ru/xml/fictionbook/2.0}imageType"/&gt;
 *                   &lt;element name="poem" type="{http://www.gribuser.ru/xml/fictionbook/2.0}poemType"/&gt;
 *                   &lt;element name="subtitle" type="{http://www.gribuser.ru/xml/fictionbook/2.0}pType"/&gt;
 *                   &lt;element name="cite" type="{http://www.gribuser.ru/xml/fictionbook/2.0}citeType"/&gt;
 *                   &lt;element name="empty-line" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                   &lt;element name="table" type="{http://www.gribuser.ru/xml/fictionbook/2.0}tableType"/&gt;
 *                 &lt;/choice&gt;
 *                 &lt;attribute name="original-location" use="required" type="{http://www.gribuser.ru/xml/fictionbook/2.0/markup}XPointer" /&gt;
 *                 &lt;attribute name="selection-text" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="selection"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;pattern value="xpointer\(point\(here\(\)(/[0-9]+)+\.[0-9]+\)/range-to\(point\(here\(\)(/[0-9]+)+\.[0-9]+\)\)\)"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.gribuser.ru/xml/fictionbook/2.0/markup}UUIDType" /&gt;
 *       &lt;attribute name="selection" use="required" type="{http://www.gribuser.ru/xml/fictionbook/2.0/markup}XRange" /&gt;
 *       &lt;attribute name="art-id" use="required" type="{http://www.w3.org/2001/XMLSchema}token" /&gt;
 *       &lt;attribute name="group" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte"&gt;
 *             &lt;minInclusive value="0"/&gt;
 *             &lt;maxInclusive value="9"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="last-update" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="class"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="30"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="title"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString"&gt;
 *             &lt;minLength value="1"/&gt;
 *             &lt;maxLength value="100"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="percent"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte"&gt;
 *             &lt;minInclusive value="0"/&gt;
 *             &lt;maxInclusive value="100"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SelectionType", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0/markup", propOrder = {
    "note",
    "extract"
})
public class SelectionType {

    @XmlElement(name = "Note")
    protected List<SelectionType.Note> note;
    @XmlElement(name = "Extract")
    protected SelectionType.Extract extract;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "selection", required = true)
    protected String selection;
    @XmlAttribute(name = "art-id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String artId;
    @XmlAttribute(name = "group", required = true)
    protected byte group;
    @XmlAttribute(name = "last-update", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastUpdate;
    @XmlAttribute(name = "class")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String clazz;
    @XmlAttribute(name = "title")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String title;
    @XmlAttribute(name = "percent")
    protected Byte percent;

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelectionType.Note }
     * 
     * 
     */
    public List<SelectionType.Note> getNote() {
        if (note == null) {
            note = new ArrayList<SelectionType.Note>();
        }
        return this.note;
    }

    /**
     * Gets the value of the extract property.
     * 
     * @return
     *     possible object is
     *     {@link SelectionType.Extract }
     *     
     */
    public SelectionType.Extract getExtract() {
        return extract;
    }

    /**
     * Sets the value of the extract property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectionType.Extract }
     *     
     */
    public void setExtract(SelectionType.Extract value) {
        this.extract = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the selection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelection() {
        return selection;
    }

    /**
     * Sets the value of the selection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelection(String value) {
        this.selection = value;
    }

    /**
     * Gets the value of the artId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtId() {
        return artId;
    }

    /**
     * Sets the value of the artId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtId(String value) {
        this.artId = value;
    }

    /**
     * Gets the value of the group property.
     * 
     */
    public byte getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     */
    public void setGroup(byte value) {
        this.group = value;
    }

    /**
     * Gets the value of the lastUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdate() {
        return lastUpdate;
    }

    /**
     * Sets the value of the lastUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdate(XMLGregorianCalendar value) {
        this.lastUpdate = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the percent property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getPercent() {
        return percent;
    }

    /**
     * Sets the value of the percent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setPercent(Byte value) {
        this.percent = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
     *         &lt;element name="p" type="{http://www.gribuser.ru/xml/fictionbook/2.0}pType"/&gt;
     *         &lt;element name="image" type="{http://www.gribuser.ru/xml/fictionbook/2.0}imageType"/&gt;
     *         &lt;element name="poem" type="{http://www.gribuser.ru/xml/fictionbook/2.0}poemType"/&gt;
     *         &lt;element name="subtitle" type="{http://www.gribuser.ru/xml/fictionbook/2.0}pType"/&gt;
     *         &lt;element name="cite" type="{http://www.gribuser.ru/xml/fictionbook/2.0}citeType"/&gt;
     *         &lt;element name="empty-line" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *         &lt;element name="table" type="{http://www.gribuser.ru/xml/fictionbook/2.0}tableType"/&gt;
     *       &lt;/choice&gt;
     *       &lt;attribute name="original-location" use="required" type="{http://www.gribuser.ru/xml/fictionbook/2.0/markup}XPointer" /&gt;
     *       &lt;attribute name="selection-text" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="selection"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;pattern value="xpointer\(point\(here\(\)(/[0-9]+)+\.[0-9]+\)/range-to\(point\(here\(\)(/[0-9]+)+\.[0-9]+\)\)\)"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pOrImageOrPoem"
    })
    public static class Extract {

        @XmlElementRefs({
            @XmlElementRef(name = "p", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0/markup", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "image", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0/markup", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "poem", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0/markup", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "subtitle", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0/markup", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "cite", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0/markup", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "empty-line", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0/markup", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "table", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0/markup", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<?>> pOrImageOrPoem;
        @XmlAttribute(name = "original-location", required = true)
        protected String originalLocation;
        @XmlAttribute(name = "selection-text")
        protected String selectionText;
        @XmlAttribute(name = "selection")
        protected String selection;

        /**
         * Gets the value of the pOrImageOrPoem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the pOrImageOrPoem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPOrImageOrPoem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link Object }{@code >}
         * {@link JAXBElement }{@code <}{@link CiteType }{@code >}
         * {@link JAXBElement }{@code <}{@link ImageType }{@code >}
         * {@link JAXBElement }{@code <}{@link PType }{@code >}
         * {@link JAXBElement }{@code <}{@link PType }{@code >}
         * {@link JAXBElement }{@code <}{@link PoemType }{@code >}
         * {@link JAXBElement }{@code <}{@link TableType }{@code >}
         * 
         * 
         */
        public List<JAXBElement<?>> getPOrImageOrPoem() {
            if (pOrImageOrPoem == null) {
                pOrImageOrPoem = new ArrayList<JAXBElement<?>>();
            }
            return this.pOrImageOrPoem;
        }

        /**
         * Gets the value of the originalLocation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOriginalLocation() {
            return originalLocation;
        }

        /**
         * Sets the value of the originalLocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOriginalLocation(String value) {
            this.originalLocation = value;
        }

        /**
         * Gets the value of the selectionText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSelectionText() {
            return selectionText;
        }

        /**
         * Sets the value of the selectionText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSelectionText(String value) {
            this.selectionText = value;
        }

        /**
         * Gets the value of the selection property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSelection() {
            return selection;
        }

        /**
         * Sets the value of the selection property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSelection(String value) {
            this.selection = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
     *         &lt;element name="p" type="{http://www.gribuser.ru/xml/fictionbook/2.0}pType"/&gt;
     *         &lt;element name="empty-line" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pOrEmptyLine"
    })
    public static class Note {

        @XmlElements({
            @XmlElement(name = "p", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0/markup", type = PType.class),
            @XmlElement(name = "empty-line", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0/markup")
        })
        protected List<Object> pOrEmptyLine;

        /**
         * Gets the value of the pOrEmptyLine property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the pOrEmptyLine property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPOrEmptyLine().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * {@link PType }
         * 
         * 
         */
        public List<Object> getPOrEmptyLine() {
            if (pOrEmptyLine == null) {
                pOrEmptyLine = new ArrayList<Object>();
            }
            return this.pOrEmptyLine;
        }

    }

}
