//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.11 at 11:44:38 PM MSK 
//


package org.jaxb.fb2;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlMixed;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Markup
 * 
 * <p>Java class for styleLinkType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="styleLinkType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="strong" type="{http://www.gribuser.ru/xml/fictionbook/2.0}styleLinkType"/&gt;
 *         &lt;element name="emphasis" type="{http://www.gribuser.ru/xml/fictionbook/2.0}styleLinkType"/&gt;
 *         &lt;element name="style" type="{http://www.gribuser.ru/xml/fictionbook/2.0}styleLinkType"/&gt;
 *         &lt;element name="strikethrough" type="{http://www.gribuser.ru/xml/fictionbook/2.0}styleLinkType"/&gt;
 *         &lt;element name="sub" type="{http://www.gribuser.ru/xml/fictionbook/2.0}styleLinkType"/&gt;
 *         &lt;element name="sup" type="{http://www.gribuser.ru/xml/fictionbook/2.0}styleLinkType"/&gt;
 *         &lt;element name="code" type="{http://www.gribuser.ru/xml/fictionbook/2.0}styleLinkType"/&gt;
 *         &lt;element name="image" type="{http://www.gribuser.ru/xml/fictionbook/2.0}inlineImageType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "styleLinkType", propOrder = {
    "content"
})
public class StyleLinkType {

    @XmlElementRefs({
        @XmlElementRef(name = "strong", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "emphasis", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "style", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "strikethrough", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sub", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sup", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "code", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "image", namespace = "http://www.gribuser.ru/xml/fictionbook/2.0", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Markup Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link InlineImageType }{@code >}
     * {@link JAXBElement }{@code <}{@link StyleLinkType }{@code >}
     * {@link JAXBElement }{@code <}{@link StyleLinkType }{@code >}
     * {@link JAXBElement }{@code <}{@link StyleLinkType }{@code >}
     * {@link JAXBElement }{@code <}{@link StyleLinkType }{@code >}
     * {@link JAXBElement }{@code <}{@link StyleLinkType }{@code >}
     * {@link JAXBElement }{@code <}{@link StyleLinkType }{@code >}
     * {@link JAXBElement }{@code <}{@link StyleLinkType }{@code >}
     * {@link String }
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

}
