file-processor:
  telegramTokenId: '7781761396:AAEvBwGqFqwQfLpQhPkG8y8luYwvnyO4ZPs'
  maxFileSize: 5_000_000
kafka-file-message:
  topic: 'income_file'
  delayOnErrorMillis: 1_000
  pollIntervalMillis: 1_000
  consumer:
    "[bootstrap.servers]": " 172.24.92.220:9092"
    "[client.id]": 'bookworm-telegram-file-proc'
    "[group.id]": 'bookworm-telegram-file-proc'
    "[max.pool.size]": 2
kafka-text-response:
  topic: 'text_response'
  producer:
    "[bootstrap.servers]": " 172.24.92.220:9092"
    "[client.id]": 'bookworm-telegram-file-proc'
kafka-file-response:
  topic: 'file_response'
  producer:
    "[bootstrap.servers]": " 172.24.92.220:9092"
    "[client.id]": 'bookworm-telegram-file-proc'
facade:
  host: localhost
  port: 8090