token-id: '7781761396:AAEvBwGqFqwQfLpQhPkG8y8luYwvnyO4ZPs'
kafka-text-response:
  topic: 'text_response'
  delayOnErrorMillis: 1_000
  pollIntervalMillis: 1_000
  consumer:
    "[bootstrap.servers]": " 172.24.92.220:9092"
    "[client.id]": 'bookworm-telegram-responder'
    "[group.id]": 'bookworm-telegram-responder'
    "[max.pool.size]": 10
kafka-file-response:
  topic: 'file_response'
  delayOnErrorMillis: 1_000
  pollIntervalMillis: 1_000
  consumer:
    "[bootstrap.servers]": " 172.24.92.220:9092"
    "[client.id]": 'bookworm-telegram-responder'
    "[group.id]": 'bookworm-telegram-responder'
    "[max.pool.size]": 1